## Dataset Loading and Serialization Demonstration

In [1]:
import pandas as pd
import pickle
import joblib
import os

file_path = '/content/ai_product_launch_dataset.csv.csv'
df = pd.read_csv(file_path)
print("Dataset loaded successfully:")
display(df.head())

Dataset loaded successfully:

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

### 1. Perform One-Hot Encoding on Categorical Features

In [2]:
categorical_cols = df.select_dtypes(include=['object', 'bool']).columns

categorical_cols = [col for col in categorical_cols if col not in ['crawl_timestamp', 'product_url', 'product_name', 'description', 'image', 'product_category_tree', 'product_specifications']]

print(f"Categorical columns identified for one-hot encoding: {categorical_cols}")

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("\nDataFrame after one-hot encoding:")
display(df_encoded.head())

Categorical columns identified for one-hot encoding: ['uniq_id', 'pid', 'is_FK_Advantage_product', 'product_rating', 'overall_rating', 'brand']

DataFrame after one-hot encoding:

,crawl_timestamp,product_url,product_name,product_category_tree,retail_price,discounted_price,image,description,product_specifications,uniq_id_0016d519d6f1aaa48e4770e6b2577334,...,brand_topolino,brand_totalcare Expert,brand_tp-Link,brand_trustedsnap,brand_urban monk creations,brand_vatika,brand_vency creation,brand_womaniya,brand_xy decor,brand_youniqueshop
0,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
1,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",False,...,False,False,False,False,False,False,False,False,False,False
2,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",Key Features of AW Bellies Sandals Wedges Heel...,"{""product_specification""=>[{""key""=>""Ideal For""...",False,...,False,False,False,False,False,False,False,False,False,False
3,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
4,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",Specifications of Sicons All Purpose Arnica Do...,"{""product_specification""=>[{""key""=>""Pet Type"",...",False,...,False,False,False,False,False,False,False,False,False,False

2.PERFORM TRAIN_TEST-SPLIT OPERATION

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import pandas as pd
df_cleaned = df_encoded.dropna(subset=['discounted_price']).copy()

X = df_cleaned.drop('discounted_price', axis=1)
y = df_cleaned['discounted_price']

X = X.select_dtypes(include=['number', 'bool'])

imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)
X = pd.DataFrame(X_imputed, columns=X.columns, index=X.index)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Original features shape (after cleaning y NaNs and imputing X NaNs): {X.shape}")
print(f"Training features shape: {X_train.shape}")

Original features shape (after cleaning y NaNs and imputing X NaNs): (8466, 18721)
Training features shape: (5926, 18721)

###  Train a Linear Regression Model

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import pickle

model = LinearRegression()

model.fit(X_train, y_train)

print("Linear Regression Model trained successfully.")

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE) on test set: {mae:.2f}")
print(f"R-squared (R2) on test set: {r2:.2f}")

pickle_model_filename = 'linear_regression_model.pkl'

with open(pickle_model_filename, 'wb') as f:
    pickle.dump(model, f)
print(f"Linear Regression model successfully pickled and saved to {pickle_model_filename}")

Linear Regression Model trained successfully.
Mean Absolute Error (MAE) on test set: 395.59
R-squared (R2) on test set: 0.98
Linear Regression model successfully pickled and saved to linear_regression_model.pkl

### **3**. Store and Load the Model using `pickle`

In [12]:

pickle_model_filename = 'linear_regression_model.pkl'
with open(pickle_model_filename, 'rb') as f:
    loaded_model_pickle = pickle.load(f)
print(f"Linear Regression model successfully loaded from {pickle_model_filename}")

loaded_model_pickle_pred = loaded_model_pickle.predict(X_test.head(1))
print(f"Prediction with loaded pickle model: {loaded_model_pickle_pred[0]:.2f}")
print(f"Actual value for the first test sample: {y_test.head(1).values[0]:.2f}")

Linear Regression model successfully loaded from linear_regression_model.pkl
Prediction with loaded pickle model: -213.56
Actual value for the first test sample: 195.00

### 4. Store and Load the Model using `joblib`

In [13]:
import joblib

joblib_model_filename = 'linear_regression_model.joblib'

joblib.dump(model, joblib_model_filename)
print(f"Linear Regression model successfully saved using joblib to {joblib_model_filename}")

loaded_model_joblib = joblib.load(joblib_model_filename)
print(f"Linear Regression model successfully loaded from {joblib_model_filename}")

loaded_model_joblib_pred = loaded_model_joblib.predict(X_test.head(1))
print(f"Prediction with loaded joblib model: {loaded_model_joblib_pred[0]:.2f}")
print(f"Actual value for the first test sample: {y_test.head(1).values[0]:.2f}")

Linear Regression model successfully saved using joblib to linear_regression_model.joblib
Linear Regression model successfully loaded from linear_regression_model.joblib
Prediction with loaded joblib model: -213.56
Actual value for the first test sample: 195.00