## Dataset Loading and Serialization Demonstration

In [1]:
import pandas as pd
import pickle
import joblib
import os

### 1. Load the dataset

In [2]:
file_path = '/content/ai_product_launch_dataset.csv.csv'
df = pd.read_csv(file_path)
display(df.head())

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

### 2. Demonstrate `pickle` for saving and loading the DataFrame

In [3]:
pickle_filename = 'dataframe.pkl'

with open(pickle_filename, 'wb') as f:
    pickle.dump(df, f)
print(f"DataFrame successfully pickled and saved to {pickle_filename}")

with open(pickle_filename, 'rb') as f:
    loaded_df_pickle = pickle.load(f)
print(f"DataFrame successfully loaded from {pickle_filename}")
display(loaded_df_pickle.head())

DataFrame successfully pickled and saved to dataframe.pkl
DataFrame successfully loaded from dataframe.pkl

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

### 3. Demonstrate `joblib` for saving and loading the DataFrame

In [6]:
joblib_filename = 'dataframe.joblib'

joblib.dump(df, joblib_filename)
print(f"DataFrame successfully saved using joblib to {joblib_filename}")

loaded_df_joblib = joblib.load(joblib_filename)
print(f"DataFrame successfully loaded from {joblib_filename}")
display(loaded_df_joblib.head())

DataFrame successfully saved using joblib to dataframe.joblib
DataFrame successfully loaded from dataframe.joblib

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

### 4. Perform One-Hot Encoding on Categorical Features

In [8]:
categorical_cols = df.select_dtypes(include=['object', 'bool']).columns

categorical_cols = [col for col in categorical_cols if col not in ['crawl_timestamp', 'product_url', 'product_name', 'description', 'image', 'product_category_tree', 'product_specifications']]

print(f"Categorical columns identified for one-hot encoding: {categorical_cols}")

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("\nDataFrame after one-hot encoding:")
display(df_encoded.head())

Categorical columns identified for one-hot encoding: ['uniq_id', 'pid', 'is_FK_Advantage_product', 'product_rating', 'overall_rating', 'brand']

DataFrame after one-hot encoding:

,crawl_timestamp,product_url,product_name,product_category_tree,retail_price,discounted_price,image,description,product_specifications,uniq_id_0005bab836087ed542c5e23111078035,...,brand_walletsnbags,brand_wallskart,brand_womaniya,brand_xpert,brand_xy decor,brand_youniqueshop,brand_zDelhi.com,brand_zaidis,brand_zasmina,brand_ Tarkan
0,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
1,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",False,...,False,False,False,False,False,False,False,False,False,False
2,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",Key Features of AW Bellies Sandals Wedges Heel...,"{""product_specification""=>[{""key""=>""Ideal For""...",False,...,False,False,False,False,False,False,False,False,False,False
3,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
4,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",Specifications of Sicons All Purpose Arnica Do...,"{""product_specification""=>[{""key""=>""Pet Type"",...",False,...,False,False,False,False,False,False,False,False,False,False
5,2016-03-25 22:59:23 +0000,http://www.flipkart.com/eternal-gandhi-super-s...,Eternal Gandhi Super Series Crystal Paper Weig...,"[""Eternal Gandhi Super Series Crystal Paper We...",430.0,430.0,"[""http://img5a.flixcart.com/image/paper-weight...",Key Features of Eternal Gandhi Super Series Cr...,"{""product_specification""=>[{""key""=>""Model Name...",False,...,False,False,False,False,False,False,False,False,False,False
6,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",1199.0,479.0,"[""http://img6a.flixcart.com/image/short/p/j/z/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/e/x...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",False,...,False,False,False,False,False,False,False,False,False,False
8,2016-03-25 22:59:23 +0000,http://www.flipkart.com/dilli-bazaaar-bellies-...,"dilli bazaaar Bellies, Corporate Casuals, Casuals","[""Footwear >> Women's Footwear >> Ballerinas >...",699.0,349.0,"[""http://img6a.flixcart.com/image/shoe/b/p/n/p...","Key Features of dilli bazaaar Bellies, Corpora...","{""product_specification""=>[{""key""=>""Occasion"",...",False,...,False,False,False,False,False,False,False,False,False,False
9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",1199.0,479.0,"[""http://img5a.flixcart.com/image/short/5/z/c/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
10,2016-03-25 22:59:23 +0000,http://www.flipkart.com/ladela-bellies/p/itmeh...,Ladela Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",1724.0,950.0,"[""http://img5a.flixcart.com/image/shoe/s/g/m/b...",Key Features of Ladela Bellies Brand: LADELA C...,"{""product_specification""=>[{""key""=>""Occasion"",...",False,...,False,False,False,False,False,False,False,False,False,False
11,2016-03-25 22:59:23 +0000,http://www.flipkart.com/carrel-printed-women-s...,Carrel Printed Women's,"[""Clothing >> Women's Clothing >> Sports & Gym...",2299.0,910.0,"[""http://img6a.flixcart.com/image/swimsuit/5/v...",Key Features of Carrel Printed Women's Fabric:...,"{""product_specification""=>[{""key""=>""Neck"", ""va...",False,...,False,False,False,False,False,False,False,False,False,False
12,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-tea...,Sicons All Purpose Tea Tree Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",NaN,NaN,"[""http://img6a.flixcart.com/image/pet-shampoo/...",Specifications of Sicons All Purpose Tea Tree ...,"{""product_specification""=>[{""key""=>""Pet Type"",...",False,...,False,False,False,False,False,False,False,False,False,False
13,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",999.0,379.0,"[""http://img6a.flixcart.com/image/short/q/z/v/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
14,2016-03-25 22:59:23 +0000,http://www.flipkart.com/freelance-vacuum-bottl...,Freelance Vacuum Bottles 350 ml Bottle,"[""Pens & Stationery >> School Supplies >> Wate...",699.0,699.0,"[""http://img5a.flixcart.com/image/bottle/j/m/m...",Specifications of Freelance Vacuum Bottles 350...,"{""product_specification""=>[{""key""=>""Body Mater...",False,...,False,False,False,False,False,False,False,False,False,False
15,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",999.0,379.0,"[""http://img5a.flixcart.com/image/short/t/p/b/...",Key Features of Alisha Solid Women's Cycling S...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
16,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",32157.0,22646.0,"[""http://img5a.flixcart.com/image/sofa-bed/r/c...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""key""=>""Installati...",False,...,False,False,False,False,False,False,False,False,False,False
17,2016-03-25 22:59:23 +0000,http://www.flipkart.com/style-foot-bellies/p/i...,Style Foot Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",899.0,449.0,"[""http://img5a.flixcart.com/image/shoe/p/f/h/b...",Key Features of Style Foot Bellies ballerina s...,"{""product_specification""=>[{""key""=>""Occasion"",...",False,...,False,False,False,False,False,False,False,False,False,False
18,2016-03-25 22:59:23 +0000,http://www.flipkart.com/carrel-printed-women-s...,Carrel Printed Women's,"[""Clothing >> Women's Clothing >> Sports & Gym...",2499.0,999.0,"[""http://img5a.flixcart.com/image/swimsuit/g/z...",Key Features of Carrel Printed Women's Fabric:...,"{""product_specification""=>[{""key""=>""Neck"", ""va...",False,...,False,False,False,False,False,False,False,False,False,False
19,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/6...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,"{""product_specification""=>[{""value""=>""1 Sofa B...",False,...,False,False,False,False,False,False,False,False,False,False
20,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-conditioning-co...,Sicons Conditioning Conditoner Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",110.0,100.0,"[""http://img6a.flixcart.com/image/pet-shampoo/...",Specifications of Sicons Conditioning Conditon...,"{""product_specification""=>[{""key""=>""Pet Type"",...",False,...,False,False,False,False,False,False,False,False,False,False
21,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",NaN,NaN,"[""http://img6a.flixcart.com/image/short/m/g/y/...",Alisha Solid Women's Cycling Shorts - Buy Blac...,NaN,False,...,False,False,False,False,False,False,False,False,False,False
22,2016-03-31 15:22:07 +0000,http://www.flipkart.com/dongli-printed-boy-s-r...,dongli Printed Boy's Round Neck T-Shirt,"[""Clothing >> Kids' Clothing >> Boys Wear >> P...",2400.0,1039.0,"[""http://img5a.flixcart.com/image/t-shirt/w/x/...",Specifications of dongli Printed Boy's Round N...,"{""product_specification""=>[{""key""=>""Sleeve"", ""...",False,...,False,False,False,False,False,False,False,False,False,False
23,2016-03-31 15:22:07 +0000,http://www.flipkart.com/swagga-women-clogs/p/i...,SWAGGA Women Clogs,"[""Footwear >> Women's Footwear >> Sports Sanda...",1500.0,1500.0,"[""http://img6a.flixcart.com/image/sandal/h/7/v...",Key Features of SWAGGA Women Clogs Occasion: E...,"{""product_specification""=>[{""key""=>""Occasion"",...",False,...,False,False,False,False,False,False,False,False,False,False
24,2016-01-03 20:56:50 +0000,http://www.flipkart.com/kennel-rubber-dumbell-...,Kennel Rubber Dumbell With Bell - Small Rubber...,"[""Pet Supplies >> Toys >> Comfort Toys""]",190.0,190.0,"[""http://img5a.flixcart.com/image/pet-toy/n/a/...",Buy Kennel Rubber Dumbell With Bell - Small Ru...,"{""product_specification""=>[{""key""=>""Pet Type"",...",False,...,False,False,False,False,False,False,False,False,False,False
25,2016-01-03 20:56:50 +0000,http://www.flipkart.com/glus-wedding-lingerie-...,Glus Wedding Lingerie Set,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",1299.0,699.0,"[""http://img5a.flixcart.com/image/lingerie-set...",Glus Wedding Lingerie Set - Buy Turquoise Glus...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
26,2016-01-03 20:56:50 +0000,http://www.flipkart.com/veelys-shiny-white-qua...,Veelys Shiny White Quad Roller Skates - Size 4...,"[""Sports & Fitness >> Other Sports >> Skating ...",3199.0,2499.0,"[""http://img6a.flixcart.com/image/skate/w/y/7/...",Veelys Shiny White Quad Roller Skates - Size 4...,"{""product_specification""=>[{""key""=>""Playing Le...",False,...,False,False,False,False,False,False,False,False,False,False
27,2016-01-03 20:56:50 +0000,http://www.flipkart.com/bulaky-vanity-case-jew...,Bulaky vanity case Jewellery Vanity Case,"[""Beauty and Personal Care >> Makeup >> Vanity...",499.0,390.0,"[""http://img6a.flixcart.com/image/vanity-box/8...",Buy Bulaky vanity case Jewellery Vanity Case f...,"{""product_specification""=>{""key""=>""Body Materi...",False,...,False,False,False,False,False,False,False,False,False,False
28,2016-01-03 20:56:50 +0000,http://www.flipkart.com/fdt-women-s-leggings/p...,FDT Women's Leggings,"[""Clothing >> Women's Clothing >> Fusion Wear ...",699.0,309.0,"[""http://img6a.flixcart.com/image/legging-jegg...",FDT Women's Leggings - Buy Parrot Green FDT Wo...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
29,2016-01-03 20:56:50 +0000,http://www.flipkart.com/madcaps-c38gr30-men-s-...,Madcaps C38GR30 Men's Cargos,"[""Clothing >> Men's Clothing >> Cargos, Shorts...",2199.0,1699.0,"[""http://img5a.flixcart.com/image/cargo/n/g/h/...",Madcaps C38GR30 Men's Cargos - Buy Green Madca...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
30,2016-05-11 09:26:02 +0000,http://www.flipkart.com/bengal-blooms-rose-art...,Bengal Blooms Rose Artificial Plant with Pot,"[""Bengal Blooms Rose Artificial Plant with Po...",799.0,579.0,"[""http://img5a.flixcart.com/image/artificial-p...",Key Features of Bengal Blooms Rose Artificial ...,"{""product_specification""=>[{""key""=>""Brand"", ""v...",False,...,False,False,False,False,False,False,False,False,False,False
31,2016-06-24 16:24:13 +0000,http://www.flipkart.com/indcrown-net-embroider...,Indcrown Net Embroidered Semi-stitched Lehenga...,"[""Clothing >> Women's Clothing >> Ethnic Wear ...",999.0,699.0,"[""http://img5a.flixcart.com/image/fabric/h/k/a...",Key Features of Indcrown Net Embroidered Semi-...,"{""product_specification""=>[{""key""=>""Fabric"", ""...",False,...,False,False,False,False,False,False,False,False,False,False
32,2016-06-24 16:24:13 +0000,http://www.flipkart.com/shopmania-music-band-a...,Shopmania Music Band A5 Notebook Spiral Bound,"[""Pens & Stationery >> Diaries & Notebooks >> ...",499.0,275.0,"[""http://img5a.flixcart.com/image/diary-notebo...",Specifications of Shopmania Music Band A5 Note...,"{""product_specification""=>[{""key""=>""Ruling"", ""...",False,...,False,False,False,False,False,False,False,False,False,False
33,2016-06-24 16:24:13 +0000,http://www.flipkart.com/shopmania-music-band-a...,Shopmania Music Band A5 Notebook Spiral Bound,"[""Pens & Stationery >> Diaries & Notebooks >> ...",499.0,275.0,"[""http://img5a.flixcart.com/image/diary-notebo...",Specifications of Shopmania Music Band A5 Note...,"{""product_specification""=>[{""key""=>""Ruling"", ""...",False,...,False,False,False,False,False,False,False,False,False,False
34,2016-06-24 16:24:13 +0000,http://www.flipkart.com/tiara-diaries-2016-201...,"Tiara Diaries 2016-2017 Designer LA Kaarta ""TA...","[""Pens & Stationery >> Diaries & Notebooks >> ...",1000.0,837.0,"[""http://img6a.flixcart.com/image/diary-notebo...",Specifications of Tiara Diaries 2016-2017 Desi...,"{""product_specification""=>[{""key""=>""Ruling"", ""...",False,...,False,False,False,False,False,False,False,False,False,False
35,2016-03-03 07:19:26 +0000,http://www.flipkart.com/kajci-embroidered-wome...,KAJCI Embroidered Women's Waistcoat,"[""Clothing >> Women's Clothing >> Formal Wear ...",1200.0,699.0,"[""http://img5a.flixcart.com/image/waistcoat/v/...",Specifications of KAJCI Embroidered Women's Wa...,"{""product_specification""=>[{""key""=>""Pattern"", ...",False,...,False,False,False,False,False,False,False,False,False,False
36,2016-03-03 07:19:26 +0000,http://www.flipkart.com/packman-8-x-10-inches-...,Packman 8 x 10 inches Security Bags Without PO...,"[""Pens & Stationery >> Office Supplies >> Pack...",350.0,298.0,"[""http://img6a.flixcart.com/image/packaging-se...",Key Features of Packman 8 x 10 inches Security...,"{""product_specification""=>[{""key""=>""Bubble Wra...",False,...,False,False,False,False,False,False,False,False,False,False
37,2016-03-03 07:19:26 +0000,http://www.flipkart.com/pick-pocket-embroidere...,Pick Pocket Embroidered Women's Waistcoat,"[""Clothing >> Women's Clothing >> Formal Wear ...",899.0,899.0,"[""http://img6a.flixcart.com/image/waistcoat/d/...",Specifications of Pick Pocket Embroidered Wome...,"{""product_specification""=>[{""key""=>""Pattern"", ...",False,...,False,False,False,False,False,False,False,False,False,False
38,2016-03-03 07:19:26 +0000,http://www.flipkart.com/angelfish-silk-potali-...,Angelfish Silk Potali Potli,"[""Bags, Wallets & Belts >> Bags >> Pouches and...",999.0,399.0,"[""http://img6a.flixcart.com/image/pouch-potli/...",Angelfish Silk Potali Potli (Multicolor) Price...,"{""product_specification""=>[{""key""=>""Closure"", ...",False,...,False,False,False,False,False,False,False,False,False,False
39,2016-03-03 07:19:26 +0000,http://www.flipkart.com/oye-boy-s-dungaree/p/i...,Oye Boy's Dungaree,"[""Clothing >> Kids' Clothing >> Boys Wear >> D...",899.0,764.0,"[""http://img6a.flixcart.com/image/dungaree-rom...",Specifications of Oye Boy's Dungaree Top Detai...,"{""product_specification""=>[{""key""=>""Number of ...",False,...,False,False,False,False,False,False,False,False,False,False
40,2016-05-26 06:31:26 +0000,http://www.flipkart.com/nuride-canvas-shoes/p/...,Nuride Canvas Shoes,"[""Footwear >> Women's Footwear >> Casual Shoes...",1999.0,1349.0,"[""http://img6a.flixcart.com/image/shoe/g/6/e/r...",Key Features of Nuride Canvas Shoes Material: ...,"{""product_specification""=>[{""key""=>""Occasion"",...",False,...,False,False,False,False,False,False,False,False,False,False
41,2016-05-26 06:31:26 +0000,http://www.flipkart.com/om-shivakriti-square-w...,OM SHIVAKRITI Square wall Clock Showpiece - ...,"[""Home Decor & Festive Needs >> Showpiece >> G...",1499.0,1499.0,"[""http://img6a.flixcart.com/image/showpiece-fi...",Key Features of OM SHIVAKRITI Square wall Cloc...,"{""product_specification""=>[{""key""=>""Brand"", ""v...",False,...,False,False,False,False,False,False,False,False,False,False
42,2016-05-26 06:31:26 +0000,http://www.flipkart.com/himmlisch-st381-magnet...,Himmlisch ST381 Magnetic Sun Shade For Maruti ...,"[""Automotive >> Accessories & Spare parts >> C...",6999.0,1899.0,"[""http://img5a.flixcart.com/image/sun-shade/5/...",Himmlisch ST381 Magnetic Sun Shade For Maruti ...,"{""product_specification""=>[{""key""=>""Brand"", ""v...",False,...,False,False,False,False,False,False,False,False,False,False
43,2016-04-05 17:56:58 +0000,http://www.flipkart.com/rapter-bnc-179-bnc-wir...,Rapter BNC-179 BNC Wire Connector,"[""Tools & Hardware >> Tools >> Hardware & Elec...",2299.0,1400.0,"[""http://img6a.flixcart.com/image/wire-joint-c...","Rapter BNC-179 BNC Wire Connector (Silver, Pac...","{""product_specification""=>[{""key""=>""Brand"", ""v...",False,...,False,False,False,False,False,False,False,False,False,False
44,2016-04-05 17:56:58 +0000,http://www.flipkart.com/vishudh-printed-women-...,Vishudh Printed Women's Straight Kurta,"[""Vishudh Printed Women's Straight Kurta""]",999.0,499.0,"[""http://img5a.flixcart.com/image/kurta/d/s/y/...",Specifications of Vishudh Printed Women's Stra...,"{""product_specification""=>[{""key""=>""Sleeve"", ""...",False,...,False,False,False,False,False,False,False,False,False,False
45,2016-04-05 17:56:58 +0000,http://www.flipkart.com/vishudh-printed-women-...,Vishudh Printed Women's Straight Kurta,"[""Vishudh Printed Women's Straight Kurta""]",899.0,449.0,"[""http://img5a.flixcart.com/image/kurta/s/c/g/...",Specifications of Vishudh Printed Women's Stra...,"{""product_specification""=>[{""key""=>""Sleeve"", ""...",False,...,False,False,False,False,False,False,False,False,False,False
46,2016-04-05 17:56:58 +0000,http://www.flipkart.com/vishudh-printed-women-...,Vishudh Printed Women's Anarkali Kurta,"[""Vishudh Printed Women's Anarkali Kurta""]",2099.0,1049.0,"[""http://img5a.flixcart.com/image/kurta/f/c/4/...",Specifications of Vishudh Printed Women's Anar...,"{""product_specification""=>[{""key""=>""Sleeve"", ""...",False,...,False,False,False,False,False,False,False,False,False,False

4.PERFORM TRAIN_TEST-SPLIT OPERATION

In [10]:
from sklearn.model_selection import train_test_split

X = df_encoded.drop('discounted_price', axis=1)
y = df_encoded['discounted_price']

X = X.select_dtypes(include=['number', 'bool'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Original features shape: {X.shape}")
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training target shape: {y_train.shape}")
print(f"Testing target shape: {y_test.shape}")

Original features shape: (20000, 43566)
Training features shape: (14000, 43566)
Testing features shape: (6000, 43566)
Training target shape: (14000,)
Testing target shape: (6000,)